
openapi: 3.0.3
info:
  title: IoTAPI Hub
  version: 1.0.0
  description: OpenAPI spec for all current routes
servers:
  - url: http://localhost:3000
paths:
  /users:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered
        '400':
          description: Validation error
        '409':
          description: Email already exists
        '500':
          description: Internal server error
    get:
      summary: Get user by ID (protected)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User found
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '400':
          description: Invalid ID param
        '500':
          description: Internal server error
  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
        '400':
          description: Validation error
        '500':
          description: Internal server error
  /households:
    post:
      summary: Register a new household (protected)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HouseholdRegistration'
      responses:
        '201':
          description: Household registered
        '401':
          description: Unauthorized
        '400':
          description: Validation error
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserRegistration:
      type: object
      properties:
        forename:
          type: string
        surname:
          type: string
        email:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    HouseholdRegistration:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
